
module.exports = function(knex, Promise) {
  return Promise.all([
    knex("days_topics").insert([
      {day_id: 1, topic_id: 1},
      {day_id: 1, topic_id: 4},
      {day_id: 2, topic_id: 1},
      {day_id: 2, topic_id: 6},
      {day_id: 3, topic_id: 1},
      {day_id: 4, topic_id: 1},
      {day_id: 5, topic_id: 7},
      {day_id: 6, topic_id: 7},
      {day_id: 6, topic_id: 8},
      {day_id: 7, topic_id: 1},
      {day_id: 7, topic_id: 9},
      {day_id: 7, topic_id: 10},
      {day_id: 7, topic_id: 8},
      {day_id: 8, topic_id: 9},
      {day_id: 8, topic_id: 8},
      {day_id: 9, topic_id: 9},
      {day_id: 9, topic_id: 8},
      {day_id: 10, topic_id: 8},
      {day_id: 11, topic_id: 2},
      {day_id: 11, topic_id: 3},
      {day_id: 12, topic_id: 1},
      {day_id: 12, topic_id: 15},
      {day_id: 13, topic_id: 1},
      {day_id: 13, topic_id: 15},
      {day_id: 14, topic_id: 16},
      {day_id: 14, topic_id: 11},
      {day_id: 14, topic_id: 7},
      {day_id: 15, topic_id: 2},
      {day_id: 15, topic_id: 3},
      {day_id: 16, topic_id: 16},
      {day_id: 16, topic_id: 13},
      {day_id: 16, topic_id: 12},
      {day_id: 17, topic_id: 1},
      {day_id: 17, topic_id: 12},
      {day_id: 17, topic_id: 13},
      {day_id: 17, topic_id: 14},
      {day_id: 18, topic_id: 13},
      {day_id: 18, topic_id: 12},
      {day_id: 18, topic_id: 4},
      {day_id: 19, topic_id: 1},
      {day_id: 20, topic_id: 1},
      {day_id: 20, topic_id: 9},
      {day_id: 21, topic_id: 5},
      {day_id: 21, topic_id: 9},
      {day_id: 21, topic_id: 8},
      {day_id: 21, topic_id: 7},
      {day_id: 22, topic_id: 2},
      {day_id: 22, topic_id: 15},
      {day_id: 23, topic_id: 12}
    ])
  ]);
};
